import jsPDF from "jspdf";
import "jspdf-autotable";

interface PDFExportOptions {
  title: string;
  subtitle?: string;
  columns: string[];
  rows: (string | number)[][];
  fileName: string;
  groupName?: string;
  locale?: string;
  stats?: { label: string; value: string | number }[];
}

export function exportPDF({
  title,
  subtitle,
  columns,
  rows,
  fileName,
  groupName,
  locale = "en",
  stats,
}: PDFExportOptions) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header — emerald green bar
  doc.setFillColor(16, 185, 129);
  doc.rect(0, 0, pageWidth, 28, "F");

  // Title text
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(title, 14, 14);

  // Subtitle / group name
  if (groupName || subtitle) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(groupName || subtitle || "", 14, 22);
  }

  // Date
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  const dateStr = new Date().toLocaleDateString(
    locale === "fr" ? "fr-FR" : "en-US",
    { year: "numeric", month: "long", day: "numeric" }
  );
  doc.text(dateStr, pageWidth - 14, 14, { align: "right" });

  let startY = 36;

  // Stats row if provided
  if (stats && stats.length > 0) {
    const statWidth = (pageWidth - 28) / Math.min(stats.length, 4);
    stats.slice(0, 4).forEach((stat, i) => {
      const x = 14 + i * statWidth;
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(120, 120, 120);
      doc.text(stat.label, x, startY);
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(16, 185, 129);
      doc.text(String(stat.value), x, startY + 7);
    });
    startY += 18;
  }

  // Table
  (doc as unknown as { autoTable: (opts: Record<string, unknown>) => void }).autoTable({
    startY,
    head: [columns],
    body: rows,
    theme: "grid",
    headStyles: {
      fillColor: [16, 185, 129],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 8,
    },
    bodyStyles: {
      fontSize: 8,
      textColor: [50, 50, 50],
    },
    alternateRowStyles: {
      fillColor: [245, 245, 245],
    },
    styles: {
      cellPadding: 3,
      lineColor: [220, 220, 220],
      lineWidth: 0.1,
    },
    margin: { left: 14, right: 14 },
  });

  // Footer on every page
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const footerY = doc.internal.pageSize.getHeight() - 8;
    doc.setFontSize(7);
    doc.setTextColor(150, 150, 150);
    doc.setFont("helvetica", "normal");
    doc.text("Generated by VillageClaq — villageclaq.com", 14, footerY);
    doc.text("Confidential — For group use only", pageWidth / 2, footerY, { align: "center" });
    doc.text(`Page ${i} / ${pageCount}`, pageWidth - 14, footerY, { align: "right" });
  }

  doc.save(`${fileName}.pdf`);
}
